// data.js

const lootTables = {
    "Echo of Andariel": [
        // Uniques
        { name: "Godslayer Crown", dropRate: 0.001, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Flickerstep", dropRate: 0.001, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Tibault's Will", dropRate: 0.001, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "X'Fal's Corroded Signet", dropRate: 0.001, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Soulbrand", dropRate: 0.001, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Banished Lord's Talisman", dropRate: 0.001, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Azurewrath", dropRate: 0.001, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Tuskhelm of Joritz the Mighty", dropRate: 0.05, isUnique: true, class: "Barbarian", imageUrl: 'tyraels_might.png' },
        { name: "Tempest Roar", dropRate: 0.05, isUnique: true, class: "Druid", imageUrl: 'tyraels_might.png' },
        { name: "Dolmen Stone", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Black River", dropRate: 0.05, isUnique: true, class: "Necromancer", imageUrl: 'tyraels_might.png' },
        { name: "Blood Moon Breeches", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Cowl of the Nameless", dropRate: 0.05, isUnique: true, class: "Rogue", imageUrl: 'tyraels_might.png' },
        { name: "Scoundrel's Leathers", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Flamescar", dropRate: 0.05, isUnique: true, class: "Sorcerer", imageUrl: 'tyraels_might.png' },
        { name: "Blue Rose", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
    ],

    "Uber Duriel": [
        // Uniques
        { name: "Godslayer Crown", dropRate: 0.001, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Flickerstep", dropRate: 0.001, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Tibault's Will", dropRate: 0.001, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "X'Fal's Corroded Signet", dropRate: 0.001, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Soulbrand", dropRate: 0.001, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Banished Lord's Talisman", dropRate: 0.001, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Azurewrath", dropRate: 0.001, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Tuskhelm of Joritz the Mighty", dropRate: 0.05, isUnique: true, class: "Barbarian", imageUrl: 'tyraels_might.png' },
        { name: "Tempest Roar", dropRate: 0.05, isUnique: true, class: "Druid", imageUrl: 'tyraels_might.png' },
        { name: "Dolmen Stone", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Black River", dropRate: 0.05, isUnique: true, class: "Necromancer", imageUrl: 'tyraels_might.png' },
        { name: "Blood Moon Breeches", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Cowl of the Nameless", dropRate: 0.05, isUnique: true, class: "Rogue", imageUrl: 'tyraels_might.png' },
        { name: "Scoundrel's Leathers", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Flamescar", dropRate: 0.05, isUnique: true, class: "Sorcerer", imageUrl: 'tyraels_might.png' },
        { name: "Blue Rose", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
    ],

    "The Beast in the Ice": [
        // Uniques
        { name: "Frostburn", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Mother's Embrace", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Fists of Fate", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Tassets of the Dawning Sky", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Paingorger's Gauntlets", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Fields of Crimson", dropRate: 0.1, isUnique: true, class: "Barbarian", imageUrl: 'tyraels_might.png' },
        { name: "100,000 Steps", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Ancients' Oath", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Battle Trance", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Hellhammer", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Ring of the Ravenous", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Insatiable Fury", dropRate: 0.1, isUnique: true, class: "Druid", imageUrl: 'tyraels_might.png' },
        { name: "Hunter's Zenith", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Waxing Gibbous", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Storm's Companion", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Unsung Ascetic's Wraps", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Bloodless Scream", dropRate: 0.1, isUnique: true, class: "Necromancer", imageUrl: 'tyraels_might.png' },
        { name: "Howl from Below", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Deathspeaker's Pendant", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Ring of Mendeln", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Mutilator Plate", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Condemnation", dropRate: 0.1, isUnique: true, class: "Rogue", imageUrl: 'tyraels_might.png' },
        { name: "Word of Hakan", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Windforce", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Eaglehorn", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Beastfall Boots", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Staff of Lam Esen", dropRate: 0.05, isUnique: true, class: "Sorcerer", imageUrl: 'tyraels_might.png' },
        { name: "Esu's Heirloom", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Gloves of the Illuminator", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "The Oculus", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Starfall Coronet", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
    ],

    "Lord Zir": [
        // Uniques
        { name: "Penitent Greaves", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Razorplate", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Temerity", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Yen's Blessing", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Ramaladni's Magnum Opus", dropRate: 0.1, isUnique: true, class: "Barbarian", imageUrl: 'tyraels_might.png' },
        { name: "Rage of Harrogath", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Gohr's Devastating Grips", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Overkill", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "The Butcher's Cleaver", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Arreat's Bearing", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Mad Wolf's Glee", dropRate: 0.1, isUnique: true, class: "Druid", imageUrl: 'tyraels_might.png' },
        { name: "Vasily's Prayer", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Greatstaff of the Crone", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Fleshrender", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "The Butcher's Cleaver", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Widheart Hunger", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Blood Artisan's Cuirass", dropRate: 0.1, isUnique: true, class: "Necromancer", imageUrl: 'tyraels_might.png' },
        { name: "Deathless Visage", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Greaves of the Empty Tomb", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Lidless Wall", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Cruor's Embrace", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Grasp of Shadow", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Eyes in the Dark", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Skyhunter", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Asheara's Khanjar", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Scoundrel's Kiss", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Staff of Endless Rage", dropRate: 0.1, isUnique: true, class: "Sorcerer", imageUrl: 'tyraels_might.png' },
        { name: "Iceheart Brais", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Raiment of the Infinite", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Esadora's Overflowing Cameo", dropRate: 0.05, isUnique: true, imageUrl: 'tyraels_might.png' },
    ],

    "Grigoire, The Galvanic Saint": [
        // Uniques
        { name: "Penitent Greaves", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Ramaladni's Magnum Opus", dropRate: 0.1, isUnique: true, class: "Barbarian", imageUrl: 'tyraels_might.png' },
        { name: "Rage of Harrogath", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Battle Trance", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "The Butcher's Cleaver", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Insatiable Fury", dropRate: 0.1, isUnique: true, class: "Druid", imageUrl: 'tyraels_might.png' },
        { name: "Hunter's Zenith", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Waxing Gibbous", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "The Butcher's Cleaver", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Earthbreaker", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Blood Artisan's Cuirass", dropRate: 0.1, isUnique: true, class: "Necromancer", imageUrl: 'tyraels_might.png' },
        { name: "Howl from Below", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Greaves of the Empty Tomb", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Ebonpiercer", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Word of Hakan", dropRate: 0.1, isUnique: true, class: "Rogue", imageUrl: 'tyraels_might.png' },
        { name: "Grasp of Shadow", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Windforce", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Saboteur's Signet", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Staff of Lam Esen", dropRate: 0.05, isUnique: true, class: "Sorcerer", imageUrl: 'tyraels_might.png' },
        { name: "Iceheart Brais", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Gloves of the Illuminator", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
        { name: "Flameweaver", dropRate: 0.1, isUnique: true, imageUrl: 'tyraels_might.png' },
    ],

    "Echos of Varshan": [
        // Uniques
        { name: "Frostburn", dropRate: 0.1, isUnique: true, imageUrl: 'frostburn.png' },
        { name: "Mother's Embrace", dropRate: 0.1, isUnique: true, imageUrl: 'mothers_embrace.png' },
        { name: "Fields of Crimson", dropRate: 0.1, isUnique: true, class: "Barbarian", imageUrl: 'fields_of_crimson.png' },
        { name: "100,000 Steps", dropRate: 0.1, isUnique: true, imageUrl: '100000_steps.png' },
        { name: "Gohr's Devastating Grips", dropRate: 0.1, isUnique: true, imageUrl: 'gohrs_devastating_grips.png' },
        { name: "Ring of Red Furor", dropRate: 0.1, isUnique: true, imageUrl: 'ring_of_red_furor.png' },
        { name: "Mad Wolf's Glee", dropRate: 0.1, isUnique: true, class: "Druid", imageUrl: 'mad_wolfs_glee.png' },
        { name: "Vasily's Prayer", dropRate: 0.1, isUnique: true, imageUrl: 'vasilys_prayer.png' },
        { name: "Greatstaff of the Crone", dropRate: 0.1, isUnique: true, imageUrl: 'greatstaff_of_the_crone.png' },
        { name: "Airidah's Inexorable Will", dropRate: 0.1, isUnique: true, imageUrl: 'airidahs_inexorable_will.png' },
        { name: "Bloodless Scream", dropRate: 0.1, isUnique: true, class: "Necromancer", imageUrl: 'blood_artisans_cuirass.png' },
        { name: "Deathless Visage", dropRate: 0.1, isUnique: true, imageUrl: 'deathless_visage.png' },
        { name: "Deathspeaker's Pendant", dropRate: 0.1, isUnique: true, imageUrl: 'deathspeakers_pendant.png' },
        { name: "Ring of the Sacrilegious Soul", dropRate: 0.1, isUnique: true, imageUrl: 'ring_of_the_sacrilegious_soul.png' },
        { name: "Condemnation", dropRate: 0.1, isUnique: true, class: "Rogue", imageUrl: 'condemnation.png' },
        { name: "Eyes in the Dark", dropRate: 0.1, isUnique: true, imageUrl: 'eyes_in_the_dark.png' },
        { name: "Skyhunter", dropRate: 0.1, isUnique: true, imageUrl: 'skyhunter.png' },
        { name: "Writhing Band of Trickery", dropRate: 0.1, isUnique: true, imageUrl: 'writhing_band_of_trickery.png' },
        { name: "Staff of Endless Rage", dropRate: 0.1, isUnique: true, class: "Sorcerer", imageUrl: 'staff_of_endless_rage.png' },
        { name: "Esu's Heirloom", dropRate: 0.1, isUnique: true, imageUrl: 'esus_heirloom.png' },
        { name: "Raiment of the Infinite", dropRate: 0.1, isUnique: true, imageUrl: 'raiment_of_the_infinite.png' },
        { name: "Tal Rasha's Iridescent Loop", dropRate: 0.1, isUnique: true, imageUrl: 'tal_rashas_iridescent_loop.png' },
    ],

};

// Lista de itens lendários genéricos
const legendaryItems = [
    { name: "Lendário 1", imageUrl: 'legendary_(1).png', isLegendary: true },
    { name: "Lendário 2", imageUrl: 'legendary_(2).png', isLegendary: true },
    { name: "Lendário 3", imageUrl: 'legendary_(3).png', isLegendary: true },
    { name: "Lendário 4", imageUrl: 'legendary_(4).png', isLegendary: true },
    { name: "Lendário 5", imageUrl: 'legendary_(5).png', isLegendary: true },
    { name: "Lendário 6", imageUrl: 'legendary_(6).png', isLegendary: true },
    { name: "Lendário 7", imageUrl: 'legendary_(7).png', isLegendary: true },
    { name: "Lendário 8", imageUrl: 'legendary_(8).png', isLegendary: true },
    { name: "Lendário 9", imageUrl: 'legendary_(9).png', isLegendary: true },
    { name: "Lendário 10", imageUrl: 'legendary_(10).png', isLegendary: true },
    { name: "Lendário 11", imageUrl: 'legendary_(11).png', isLegendary: true },
    { name: "Lendário 12", imageUrl: 'legendary_(12).png', isLegendary: true },
    { name: "Lendário 13", imageUrl: 'legendary_(13).png', isLegendary: true },
    { name: "Lendário 14", imageUrl: 'legendary_(14).png', isLegendary: true },
    { name: "Lendário 15", imageUrl: 'legendary_(15).png', isLegendary: true },
    { name: "Lendário 16", imageUrl: 'legendary_(16).png', isLegendary: true },
    { name: "Lendário 17", imageUrl: 'legendary_(17).png', isLegendary: true },
    { name: "Lendário 18", imageUrl: 'legendary_(18).png', isLegendary: true },
    { name: "Lendário 19", imageUrl: 'legendary_(19).png', isLegendary: true },
    { name: "Lendário 20", imageUrl: 'legendary_(20).png', isLegendary: true },
    { name: "Lendário 21", imageUrl: 'legendary_(21).png', isLegendary: true },
    { name: "Lendário 22", imageUrl: 'legendary_(22).png', isLegendary: true },
    { name: "Lendário 23", imageUrl: 'legendary_(23).png', isLegendary: true },
    { name: "Lendário 24", imageUrl: 'legendary_(24).png', isLegendary: true },
    { name: "Lendário 25", imageUrl: 'legendary_(25).png', isLegendary: true },
    { name: "Lendário 26", imageUrl: 'legendary_(26).png', isLegendary: true },
    { name: "Lendário 27", imageUrl: 'legendary_(27).png', isLegendary: true },
    { name: "Lendário 28", imageUrl: 'legendary_(28).png', isLegendary: true },
    { name: "Lendário 29", imageUrl: 'legendary_(29).png', isLegendary: true },
    { name: "Lendário 30", imageUrl: 'legendary_(30).png', isLegendary: true },
    { name: "Lendário 31", imageUrl: 'legendary_(31).png', isLegendary: true },
    { name: "Lendário 32", imageUrl: 'legendary_(32).png', isLegendary: true },
    { name: "Lendário 33", imageUrl: 'legendary_(33).png', isLegendary: true },
    { name: "Lendário 34", imageUrl: 'legendary_(34).png', isLegendary: true },
    { name: "Lendário 35", imageUrl: 'legendary_(35).png', isLegendary: true },
    { name: "Lendário 36", imageUrl: 'legendary_(36).png', isLegendary: true },
    { name: "Lendário 37", imageUrl: 'legendary_(37).png', isLegendary: true },
    { name: "Lendário 38", imageUrl: 'legendary_(38).png', isLegendary: true },
    { name: "Lendário 39", imageUrl: 'legendary_(39).png', isLegendary: true },
    { name: "Lendário 40", imageUrl: 'legendary_(40).png', isLegendary: true },
    { name: "Lendário 41", imageUrl: 'legendary_(41).png', isLegendary: true },
    { name: "Lendário 42", imageUrl: 'legendary_(42).png', isLegendary: true },
    { name: "Lendário 43", imageUrl: 'legendary_(43).png', isLegendary: true },
    { name: "Lendário 44", imageUrl: 'legendary_(44).png', isLegendary: true },
    { name: "Lendário 45", imageUrl: 'legendary_(45).png', isLegendary: true },
    { name: "Lendário 46", imageUrl: 'legendary_(46).png', isLegendary: true },
    { name: "Lendário 47", imageUrl: 'legendary_(47).png', isLegendary: true },
    { name: "Lendário 48", imageUrl: 'legendary_(48).png', isLegendary: true },
    { name: "Lendário 49", imageUrl: 'legendary_(49).png', isLegendary: true },
    { name: "Lendário 50", imageUrl: 'legendary_(50).png', isLegendary: true },
    { name: "Lendário 51", imageUrl: 'legendary_(51).png', isLegendary: true },
    { name: "Lendário 52", imageUrl: 'legendary_(52).png', isLegendary: true },
    { name: "Lendário 53", imageUrl: 'legendary_(53).png', isLegendary: true },
    { name: "Lendário 54", imageUrl: 'legendary_(54).png', isLegendary: true },
    { name: "Lendário 55", imageUrl: 'legendary_(55).png', isLegendary: true },
    { name: "Lendário 56", imageUrl: 'legendary_(56).png', isLegendary: true },
    { name: "Lendário 57", imageUrl: 'legendary_(57).png', isLegendary: true },
    { name: "Lendário 58", imageUrl: 'legendary_(58).png', isLegendary: true },
    { name: "Lendário 59", imageUrl: 'legendary_(59).png', isLegendary: true },
    { name: "Lendário 60", imageUrl: 'legendary_(60).png', isLegendary: true },
    { name: "Lendário 61", imageUrl: 'legendary_(61).png', isLegendary: true },
    { name: "Lendário 62", imageUrl: 'legendary_(62).png', isLegendary: true },
    { name: "Lendário 63", imageUrl: 'legendary_(63).png', isLegendary: true },
    { name: "Lendário 64", imageUrl: 'legendary_(64).png', isLegendary: true },
    { name: "Lendário 65", imageUrl: 'legendary_(65).png', isLegendary: true },
    { name: "Lendário 66", imageUrl: 'legendary_(66).png', isLegendary: true },
    { name: "Lendário 67", imageUrl: 'legendary_(67).png', isLegendary: true },
    { name: "Lendário 68", imageUrl: 'legendary_(68).png', isLegendary: true },
    { name: "Lendário 69", imageUrl: 'legendary_(69).png', isLegendary: true },
    { name: "Lendário 70", imageUrl: 'legendary_(70).png', isLegendary: true },
    { name: "Lendário 71", imageUrl: 'legendary_(71).png', isLegendary: true },
    { name: "Lendário 72", imageUrl: 'legendary_(72).png', isLegendary: true },
    { name: "Lendário 73", imageUrl: 'legendary_(73).png', isLegendary: true },
    { name: "Lendário 74", imageUrl: 'legendary_(74).png', isLegendary: true },
    { name: "Lendário 75", imageUrl: 'legendary_(75).png', isLegendary: true },
    { name: "Lendário 76", imageUrl: 'legendary_(76).png', isLegendary: true },
    { name: "Lendário 77", imageUrl: 'legendary_(77).png', isLegendary: true },
    { name: "Lendário 78", imageUrl: 'legendary_(78).png', isLegendary: true },
    { name: "Lendário 79", imageUrl: 'legendary_(79).png', isLegendary: true },
    { name: "Lendário 80", imageUrl: 'legendary_(80).png', isLegendary: true },
    { name: "Lendário 81", imageUrl: 'legendary_(81).png', isLegendary: true },
    { name: "Lendário 82", imageUrl: 'legendary_(82).png', isLegendary: true },
    { name: "Lendário 83", imageUrl: 'legendary_(83).png', isLegendary: true },
    { name: "Lendário 84", imageUrl: 'legendary_(84).png', isLegendary: true },
    { name: "Lendário 85", imageUrl: 'legendary_(85).png', isLegendary: true },
    { name: "Lendário 86", imageUrl: 'legendary_(86).png', isLegendary: true },
    { name: "Lendário 87", imageUrl: 'legendary_(87).png', isLegendary: true },
    { name: "Lendário 88", imageUrl: 'legendary_(88).png', isLegendary: true },
    { name: "Lendário 89", imageUrl: 'legendary_(89).png', isLegendary: true },
    { name: "Lendário 90", imageUrl: 'legendary_(90).png', isLegendary: true },
    { name: "Lendário 91", imageUrl: 'legendary_(91).png', isLegendary: true },
    { name: "Lendário 92", imageUrl: 'legendary_(92).png', isLegendary: true },
    { name: "Lendário 93", imageUrl: 'legendary_(93).png', isLegendary: true },
    { name: "Lendário 94", imageUrl: 'legendary_(94).png', isLegendary: true },
    { name: "Lendário 95", imageUrl: 'legendary_(95).png', isLegendary: true },
    { name: "Lendário 96", imageUrl: 'legendary_(96).png', isLegendary: true },
    { name: "Lendário 97", imageUrl: 'legendary_(97).png', isLegendary: true },
    { name: "Lendário 98", imageUrl: 'legendary_(98).png', isLegendary: true },
    { name: "Lendário 99", imageUrl: 'legendary_(99).png', isLegendary: true },
    { name: "Lendário 100", imageUrl: 'legendary_(100).png', isLegendary: true },
    { name: "Lendário 101", imageUrl: 'legendary_(101).png', isLegendary: true },
    { name: "Lendário 102", imageUrl: 'legendary_(102).png', isLegendary: true },
    { name: "Lendário 103", imageUrl: 'legendary_(103).png', isLegendary: true },
    { name: "Lendário 104", imageUrl: 'legendary_(104).png', isLegendary: true },
    { name: "Lendário 105", imageUrl: 'legendary_(105).png', isLegendary: true },
    { name: "Lendário 106", imageUrl: 'legendary_(106).png', isLegendary: true },
    { name: "Lendário 107", imageUrl: 'legendary_(107).png', isLegendary: true },
    { name: "Lendário 108", imageUrl: 'legendary_(108).png', isLegendary: true },
    { name: "Lendário 109", imageUrl: 'legendary_(109).png', isLegendary: true },
    { name: "Lendário 110", imageUrl: 'legendary_(110).png', isLegendary: true },
    { name: "Lendário 111", imageUrl: 'legendary_(111).png', isLegendary: true },
    { name: "Lendário 112", imageUrl: 'legendary_(112).png', isLegendary: true },
    { name: "Lendário 113", imageUrl: 'legendary_(113).png', isLegendary: true },
    { name: "Lendário 114", imageUrl: 'legendary_(114).png', isLegendary: true },
    { name: "Lendário 115", imageUrl: 'legendary_(115).png', isLegendary: true },
    { name: "Lendário 116", imageUrl: 'legendary_(116).png', isLegendary: true },
    { name: "Lendário 117", imageUrl: 'legendary_(117).png', isLegendary: true },
    { name: "Lendário 118", imageUrl: 'legendary_(118).png', isLegendary: true },
    { name: "Lendário 119", imageUrl: 'legendary_(119).png', isLegendary: true },
    { name: "Lendário 120", imageUrl: 'legendary_(120).png', isLegendary: true },
    { name: "Lendário 121", imageUrl: 'legendary_(121).png', isLegendary: true },
    { name: "Lendário 122", imageUrl: 'legendary_(122).png', isLegendary: true },
    { name: "Lendário 123", imageUrl: 'legendary_(123).png', isLegendary: true },
    { name: "Lendário 124", imageUrl: 'legendary_(124).png', isLegendary: true },
    { name: "Lendário 125", imageUrl: 'legendary_(125).png', isLegendary: true },
    { name: "Lendário 126", imageUrl: 'legendary_(126).png', isLegendary: true },
    { name: "Lendário 127", imageUrl: 'legendary_(127).png', isLegendary: true },
    { name: "Lendário 128", imageUrl: 'legendary_(128).png', isLegendary: true },
    { name: "Lendário 129", imageUrl: 'legendary_(129).png', isLegendary: true },
    { name: "Lendário 130", imageUrl: 'legendary_(130).png', isLegendary: true },
    { name: "Lendário 131", imageUrl: 'legendary_(131).png', isLegendary: true },
    { name: "Lendário 132", imageUrl: 'legendary_(132).png', isLegendary: true },
    { name: "Lendário 133", imageUrl: 'legendary_(133).png', isLegendary: true },
    { name: "Lendário 134", imageUrl: 'legendary_(134).png', isLegendary: true },
    { name: "Lendário 135", imageUrl: 'legendary_(135).png', isLegendary: true },
    { name: "Lendário 136", imageUrl: 'legendary_(136).png', isLegendary: true },
    { name: "Lendário 137", imageUrl: 'legendary_(137).png', isLegendary: true },
    { name: "Lendário 138", imageUrl: 'legendary_(138).png', isLegendary: true },
    { name: "Lendário 139", imageUrl: 'legendary_(139).png', isLegendary: true },
    { name: "Lendário 140", imageUrl: 'legendary_(140).png', isLegendary: true },
    { name: "Lendário 141", imageUrl: 'legendary_(141).png', isLegendary: true },
    { name: "Lendário 142", imageUrl: 'legendary_(142).png', isLegendary: true },
    { name: "Lendário 143", imageUrl: 'legendary_(143).png', isLegendary: true },
    { name: "Lendário 144", imageUrl: 'legendary_(144).png', isLegendary: true },
];


const mythicUniques = [
    { name: "The Grandfather", dropRate: 0.15, class: ["Barbarian, Necromancer"], rarity: "Uber Rare", imageUrl: 'the_grandfather.png' },
    { name: "Ahavarion, Spear of Lycander", dropRate: 0.015, class: ["Druid, Sorcerer"], rarity: "Uber Rare", imageUrl: 'ahavarion_spear_of_lycander.png' },
    { name: "Doombringer", dropRate: 0.015, rarity: "Uber Rare", imageUrl: 'doombringer.png' },
    { name: "Melted Heart of Selig", dropRate: 0.015, rarity: "Uber Rare", imageUrl: 'melted_heart_of_selig.png' },
    { name: "Andariel's Visage", dropRate: 0.015, rarity: "Uber Rare", imageUrl: 'andariels_visage.png' },
    { name: "Harlequin Crest", dropRate: 0.015, rarity: "Uber Rare", imageUrl: 'harlequin_crest.png' },
    { name: "Tyreal's Might", dropRate: 0.015, rarity: "Uber Rare", imageUrl: 'tyraels_might.png' },
    { name: "Ring of Starless Skies", dropRate: 0.015, rarity: "Uber Rare", imageUrl: 'ring_of_starless_skies.png' },
];

module.exports = { lootTables, legendaryItems, mythicUniques };